### ISSUE TITLE
Communication Lines not showing

### ISSUE THREAD

**Issue by JohnN6** [OddLingo/js8map#4]
Version looking good now, but it seems to have stopped drawing lines between stations.   The short term immediate comm9nation line - 1 cycle 15 secs appears, but no others.  Circles showing up.

It now begins to give a useful aide memoire as to where stations are.  I ran a debugger today and could not see an obvious fault.

**Comment by OddLingo** [comment]
The callbook.dat file grows all the time, so more and more stations will appear.
The yellow 'link' lines have been changed so that they only last for one cycle, as the map was getting too cluttered if you left it running for hours.  But I am working on a separate mode where each station accumulates the callsigns of all other stations it has ever heard during the current session and those can be displayed as fainter grey lines.  This will be activated as a "Show history" checkbox under the "View" menu item.

**Comment by OddLingo** [comment]
I think this is working in version 0..55.   The yellow lines represent immediate communcations.  The "history" mode (enabled under the View menu) shows all links this session, as fainter grey lines.

**Comment by JohnN6** [comment]
Interestingly none of the menus are working on my system - but   I DON’T think this is a bug, but just a side effect because I have been running it under Thonny which is an IDE with its own full Python inside it.  I started doing this with my old iMac which did not have Python 3 and keeping two Python’s running was such a mess !

I’ll have a go with python proper, but might have to update the modules if they are not present on an iMac
John N.

**Comment by OddLingo** [comment]
If you just type a lower case "h" at the map window it should also toggle history mode.  Try that
